idf_component_register(SRCS "blink_example_main.c"
                            "entities/player.c"
                            "../drivers/ILI9341.c"
                         #    "../drivers/esp_family/ESP32.c"
                            "../drivers/esp_family/ESP32-S3.c"
                            "../maps/TestLevel.c"
                            "../tiles/tiles.c"
                            "utility/physics.c"
                            "entities/entity.c"
                            "entities/bomb.c"
                            "../maps/level_manager.c"
                            "networking/network.c"
                       INCLUDE_DIRS "."
                                    "../drivers"
                       REQUIRES esp_adc esp_timer esp_wifi nvs_flash esp_netif lwip esp_event)