/* Auto-generated by tilemap_editor.py � do not edit manually */
#ifndef TESTLEVEL_H
#define TESTLEVEL_H

#include <stdint.h>


/* Flag bit masks */
#define TILE_FLAG_FLIP_X      0x01
#define TILE_FLAG_FLIP_Y      0x02
#define TILE_FLAG_SOLID       0x04
#define TILE_FLAG_PASSTHROUGH 0x08
#define TILE_TYPE_MASK        0xF0
#define TILE_TYPE_SHIFT       4

/* Tile type values */
#define TILE_TYPE_NONE         0
#define TILE_TYPE_PLATFORM     1
#define TILE_TYPE_WALL         2
#define TILE_TYPE_HAZARD       3
#define TILE_TYPE_COLLECTIBLE  4
#define TILE_TYPE_DECORATION   5
#define TILE_TYPE_SPAWN        6

#define LVL_TESTLEVEL_TILECOUNT 33*15
#define LVL_TESTLEVEL_WIDTH 33
#define LVL_TESTLEVEL_HEIGHT 15

extern const uint8_t TestLevel_tiles[LVL_TESTLEVEL_TILECOUNT];
extern const uint8_t TestLevel_flags[15][33];

#endif /* TESTLEVEL_H */
