"""
convert.py — Convert grayscale PNG tiles to 4-bit C arrays
Usage: python convert.py

Reads all PNGs from raw/ folder and writes:
  - tiles.c and tiles.h  (C arrays for embedding in firmware)
  - converted/           (preview PNGs showing the 4-bit quantized result)
"""

import os
from PIL import Image

RAW_DIR = "tileImport"
CONVERTED_DIR = "tileImportConverted"
OUTPUT_C = "tiles/tiles.c"
OUTPUT_H = "tiles/tiles.h"
print("cwd =", os.getcwd())
print("RAW_DIR =", os.path.abspath(RAW_DIR))
print("exists =", os.path.exists(RAW_DIR))

def convert_tile(img_path):
    """Convert a PNG to 4-bit grayscale. Returns packed bytes, preview image, w, h."""
    img = Image.open(img_path).convert("L")  # L = 8-bit grayscale
    #img = img.transpose(Image.ROTATE_90)           # <-- 90° counter-clockwise
    w, h = img.size
    pixels = list(img.getdata())

    # Quantize 8-bit (0-255) to 4-bit (0-15) then back to 8-bit for preview
    pixels_4bit    = [p >> 4 for p in pixels]
    pixels_preview = [v * 17 for v in pixels_4bit]  # 0x0F * 17 = 0xFF

    # Pack two pixels per byte (high nibble | low nibble)
    packed = []
    for i in range(0, len(pixels_4bit), 2):
        high = pixels_4bit[i] & 0x0F
        low  = pixels_4bit[i + 1] & 0x0F if (i + 1) < len(pixels_4bit) else 0
        packed.append((high << 4) | low)

    # Build preview image from quantized pixels
    preview = Image.new("L", (w, h))
    preview.putdata(pixels_preview)

    return packed, preview, w, h


def name_from_file(filename):
    """Convert filename to a valid C identifier."""
    name = os.path.splitext(filename)[0]
    name = name.replace("-", "_").replace(" ", "_")
    return f"tile_{name}"


def main():
    png_files = [f for f in os.listdir(RAW_DIR) if f.endswith(".png")]

    if not png_files:
        print(f"No PNG files found in {RAW_DIR}/")
        return

    # Create converted/ output folder if it doesn't exist
    os.makedirs(CONVERTED_DIR, exist_ok=True)

    c_lines = []
    h_lines = []

    c_lines.append("/* Auto-generated by convert.py — do not edit manually */")
    c_lines.append('#include "tiles.h"')
    c_lines.append("")

    h_lines.append("/* Auto-generated by convert.py — do not edit manually */")
    h_lines.append("#ifndef TILES_H")
    h_lines.append("#define TILES_H")
    h_lines.append("")
    h_lines.append("#include <stdint.h>")
    h_lines.append("")
    h_lines.append("/* Each tile is 8x8 pixels, 4-bit grayscale, 2 pixels per byte = 32 bytes */")
    h_lines.append("#define TILE_W    8")
    h_lines.append("#define TILE_H    8")
    h_lines.append("")

    for filename in sorted(png_files):
        path  = os.path.join(RAW_DIR, filename)
        packed, preview, w, h = convert_tile(path)
        cname = name_from_file(filename)

        # Save preview PNG to converted/ folder
        # Scale up 8x so tiny tiles are visible (8x8 -> 64x64)
        scale = 8
        preview_scaled = preview.resize((w * scale, h * scale), Image.NEAREST)
        preview_path = os.path.join(CONVERTED_DIR, filename)
        preview_scaled.save(preview_path)

        print(f"  {filename} -> {cname}[] ({len(packed)} bytes, {w}x{h}) -> converted/{filename}")

        # Write C array
        c_lines.append(f"const uint8_t {cname}[] = {{")
        for i in range(0, len(packed), 8):
            row     = packed[i:i+8]
            hex_vals = ", ".join(f"0x{b:02X}" for b in row)
            c_lines.append(f"    {hex_vals},")
        c_lines.append("};")
        c_lines.append("")

        # Write header declaration
        h_lines.append(f"extern const uint8_t {cname}[];")

    h_lines.append("")
    h_lines.append("#endif /* TILES_H */")

    # Write C files
    with open(OUTPUT_C, "w") as f:
        f.write("\n".join(c_lines) + "\n")

    with open(OUTPUT_H, "w") as f:
        f.write("\n".join(h_lines) + "\n")

    print(f"\nWrote {OUTPUT_C} and {OUTPUT_H}")
    print(f"Previews saved to {CONVERTED_DIR}/")
    print(f"Total tiles: {len(png_files)}")
    print(f"Total flash usage: {len(png_files) * 32} bytes")


if __name__ == "__main__":
    main()