/* Auto-generated by convert.py — do not edit manually */
#ifndef TILES_H
#define TILES_H

#include <stdint.h>

/* Each tile is 8x8 pixels, 4-bit grayscale, 2 pixels per byte = 32 bytes */
#define TILE_W    8
#define TILE_H    8

extern const uint8_t tile_background[];
extern const uint8_t tile_block[];
extern const uint8_t tile_bomb[];
extern const uint8_t tile_brick[];
extern const uint8_t tile_fireball[];
extern const uint8_t tile_player[];
extern const uint8_t tile_player_fall[];
extern const uint8_t tile_player_rise[];
extern const uint8_t tile_player_wall[];
extern const uint8_t tile_stair[];
extern const uint8_t tile_star[];

#endif /* TILES_H */
